# This configuration uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
keys:
  - &github_nixos_token age1t5a8ze9g5y888hv37ul78v4dfy7dtads0zkjda6720lytw6y43cssu47n9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *github_nixos_token
