name: Build system configurations

on:
  pull_request:

jobs:
  build-x86_64-netsanet:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: Jayllyz/free-disk-space@perf/use-rmz
      - uses: actions/checkout@v4
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Build netsanet
        run: |
          # nix flake check --all-systems
          nix build .#nixosConfigurations.netsanet.config.system.build.toplevel
